name: release
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build
      run: |
        GIT_REV=$(git describe --always --tags --abbrev=8 --dirty)
        LDFLAGS="-X main.gitrev=${GIT_REV}"
        GOARCH=amd64 GOOS=linux go build -ldflags "${LDFLAGS}" -o tunaworks-server cli/server/server_main.go
       
        CGO_ENABLED=0 GOARCH=amd64 GOOS=linux go build -ldflags "${LDFLAGS}" -o tunaworks-prober.linux.x86_64 cli/prober/prober_main.go
        CGO_ENABLED=0 GOARCH=amd64 GOOS=darwin go build -ldflags "${LDFLAGS}" -o tunaworks-prober.macos cli/prober/prober_main.go
        CGO_ENABLED=0 GOARCH=amd64 GOOS=windows go build -ldflags "${LDFLAGS}" -o tunaworks-prober.win64.exe cli/prober/prober_main.go
        CGO_ENABLED=0 GOARCH=arm64 GOOS=linux go build -ldflags "${LDFLAGS}" -o tunaworks-prober.linux.arm64 cli/prober/prober_main.go
        CGO_ENABLED=0 GOARCH=arm GOOS=linux go build -ldflags "${LDFLAGS}" -o tunaworks-prober.linux.arm cli/prober/prober_main.go
        CGO_ENABLED=0 GOARCH=mipsle GOOS=linux GOMIPS=softfloat go build -ldflags "${LDFLAGS}" -o tunaworks-prober.linux.mipsle cli/prober/prober_main.go
        CGO_ENABLED=0 GOARCH=mips GOOS=linux GOMIPS=softfloat go build -ldflags "${LDFLAGS}" -o tunaworks-prober.linux.mipsbe cli/prober/prober_main.go
        ./tunaworks-prober.linux.x86_64 -h
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
    - name: Upload Artifacts
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        tag_name="${GITHUB_REF##*/}"
        hub release edit $(find . -type f -executable -name "tunaworks-*" -printf "-a %p ") -m "" "$tag_name" 
